### ISSUE TITLE
Import from email doesn't always save

### ISSUE THREAD

**Issue by birdbraintech** [BirdBrainTechnologies/HummingbirdDragAndDrop-#2]
Sometimes when I import a program from email, and then hit save, and then open a different project/close the app, and then go back to the project I imported earlier, the project is blank. 

It seemed like this wasn't a problem when I did the following:

Import from email
Save As a new project name

The problem seems to be when I hit save instead of save as.

**Comment by ghost** [comment]
Is this still an issue?
